[versions]
activityKtx = "1.12.1"
ambilwarna = "2.0.1"
androidxJunit = "1.3.0"
biometric = "1.2.0-alpha05"
compilerVersion = "5.0.5"
coreKtxVersion = "1.17.0"
datastorePreferences = "1.2.0"
espressoCoreVersion = "3.7.0"
fragmentKtx = "1.8.9"
glide = "5.0.5"
gridlayout = "1.1.0"
gsonVersion = "2.13.2"
junit = "4.13.2"
appcompat = "1.7.1"
lifecycleLivedataKtxVersion = "2.10.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewmodelKtxVersion = "2.10.0"
lottieVersion = "6.7.1"
constraintlayout = "2.2.1"
materialVersion = "1.13.0"
navigationFragment = "2.9.6"
okhttp = "5.3.2"
osmdroidAndroid = "6.1.20"
osmdroidWms = "6.1.20"
playServicesLocationVersion = "21.3.0"
playServicesMapsVersion = "19.2.0"
recyclerview = "1.4.0"
roomCompilerVersion = "2.8.4"
roomRuntime = "2.8.4"
roomRuntimeVersion = "2.8.4"
shimmer = "0.5.0"
swiperefreshlayout = "1.2.0"
ucrop = "2.2.8"

[libraries]
ambilwarna = { module = "yuku.ambilwarna:ambilwarna", version.ref = "ambilwarna" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core-ktx-v1131 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-livedata-ktx-v270 = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtxVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx-v270 = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler-v261 = { module = "androidx.room:room-compiler", version.ref = "roomCompilerVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntimeVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
compiler-v4151 = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
glide-v4151 = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson-v2101 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie-v660 = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
osmdroid-wms-v6110 = { module = "org.osmdroid:osmdroid-wms", version.ref = "osmdroidWms" }
play-services-location-v2101 = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
play-services-maps-v1820 = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
yalantis-ucrop = { module = "com.github.yalantis:uCrop", version.ref = "ucrop" }


